version: '3.7'

services:

  dockerized-react:
    container_name: dockerized-react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
