export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const ACCESS_ERROR = 'ACCESS_ERROR';

export const DOCUMENTS_LIST = 'DOCUMENTS_LIST';
export const DOCUMENT_ERROR = 'DOCUMENT_ERROR';
export const DOCUMENT_EXISTS = 'DOCUMENT_EXISTS';
export const DOCUMENT_CREATED = 'DOCUMENT_CREATED';
export const VIEW_DOCUMENT = 'VIEW_DOCUMENT';
export const DOCUMENT_UPDATED = 'DOCUMENT_UPDATED';
export const SEARCH_DOCUMENTS = 'SEARCH_DOCUMENTS';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';

export const ROLE_CREATED = 'ROLE_CREATED';
export const ROLE_ERROR = 'ROLE_ERROR';
export const NO_ROLES = 'NO_ROLES';
export const VIEW_ROLE = 'VIEW_ROLE';
export const ROLE_UPDATED = 'ROLE_UPDATED';
export const ROLE_UPDATE_ERROR = 'ROLE_UPDATE_ERROR';
export const ROLE_DELETED = 'ROLE_DELETED';

export const GET_USERS_LIST = 'GET_USERS_LIST';
export const ERROR = 'ERROR';
export const VIEW_USER = 'VIEW_USER';
export const SEARCH_USERS = 'SEARCH_USERS';
export const USER_DOCUMENTS = 'USER_DOCUMENTS';
export const UPDATE_EMAIL_EXISTS = 'UPDATE_EMAIL_EXISTS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const DELETE_USER = 'DELETE_USER';
export const USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST';
export const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';
